### PR TITLE
Push rejection detection using RemoteRefUpdate status

### PR DESCRIPTION
**Pull request by mirvnillith**
The main point of this PR is GitTaskUtils.validateRemoteRefUpdates, but there are also some formatting (I've tried to align with you, but I guess some of my earlier sins were merged into your codebase).
I also fixed newlines (I'm on Windows) so the diffs should work better (although GitTasks and TagTask don't)!

### CODE REVIEW

**Comment by mirvnillith** [comment]
As a novice in git I did not work out how to branch off of an old commit (I wanted to keep this separate, but then I should've branched before the other stuff here), so one more feature went into this PR: the ability to delete a remote branch using push.

**Comment by yveszoundi** [comment]
- I'm under Unix/Linux all the time, some I'm not really sure that I want to integrate "Java files have Unix newlines" -> bb76fa4. Also see https://help.github.com/articles/dealing-with-line-endings/. Could you remove that commit?

- It looks good, if you could avoid formatting entire files all the time, that would be good. Again, with a small codebase it's not really a problem.

- Just for tracking purposes it's also good to associate pull requests to tickets as much as possible. I created a new one #17.

That's fine for the git workflow and commands, as long as you realize what could've been done better and keep learning/improving, it's all good :-). In the Open Source world, I try to keep workflow simple, avoid anarchy but allow people to contribute easily.

Thanks, would you like to be added as a collaborator, as you're actively contributing to this project?

Yves

**Comment by mirvnillith** [comment]
- That's exactly where I came from and chose the "per repository" option. How do I remove a commit?
- I'll disable my format-on-save option for this project.
- Ok, I'll do tickets as well (didn't think of it before)

Thank you for understandin and I agree, it's a versioning system so you can always go back!

**Comment by mirvnillith** [comment]
Oh, and I'd be proud to be named a collaborator as this lib really saved us a lot of work (we came from SVN, had everything automated just so and kind of rushed the git migration quite close to a major release).

**Pull request merged**
